(function () {
  'use strict';
  var K = Karts, $ = function (id) { return document.getElementById(id); }, canvas = $('circuit'), ctx = canvas.getContext('2d');
  var selectedTrack = 0, selectedCar = 0, s = K.make(0, 0), input = { assist: true }, running = false, paused = false, blocked = true, gate, audio, sound = false, last = 0, accumulator = 0, shown = false, pointerKeys = {};
  var w = 800, h = 600, zoom = 1, cx = 0, cy = 0, skid = [];
  function resize() { w = innerWidth; h = innerHeight; var d = Math.min(devicePixelRatio || 1, 1.5); canvas.width = Math.round(w * d); canvas.height = Math.round(h * d); ctx.setTransform(d, 0, 0, d, 0, 0); zoom = Math.min((w - 26) / 845, (h - 170) / 590); cx = w / 2; cy = h / 2 + 12; }
  function allowed() { if (gate) gate.check(); return !blocked; }
  function clearInput() { var assist = input.assist; input = { assist: assist }; pointerKeys = {}; document.querySelectorAll('[data-input]').forEach(function (b) { b.classList.remove('held'); }); }
  function tone(frequency) { if (!sound || blocked) return; try { audio = audio || new (window.AudioContext || window.webkitAudioContext)(); var o = audio.createOscillator(), g = audio.createGain(); o.frequency.value = frequency; o.type = 'triangle'; g.gain.setValueAtTime(.065, audio.currentTime); g.gain.exponentialRampToValueAtTime(.001, audio.currentTime + .12); o.connect(g); g.connect(audio.destination); o.start(); o.stop(audio.currentTime + .13); } catch (_) {} }
  function choices(id, list, isCar) { list.forEach(function (item, i) { var b = document.createElement('button'); b.className = i === 0 ? 'selected' : ''; b.setAttribute('aria-label', item.name); b.setAttribute('aria-pressed', String(i === 0)); b.dataset.choice = String(i); if (isCar) { var swatch = document.createElement('span'); swatch.className = 'swatch'; swatch.style.background = item.color; b.appendChild(swatch); } else b.textContent = item.icon; b.onclick = function () { if (!allowed()) return; if (isCar) selectedCar = i; else selectedTrack = i; $(id).querySelectorAll('button').forEach(function (el, j) { el.classList.toggle('selected', j === i); el.setAttribute('aria-pressed', String(j === i)); }); if (!running) s = K.make(selectedTrack, selectedCar); }; $(id).appendChild(b); }); }
  choices('cars', K.cars, true); choices('tracks', K.tracks, false);
  function start() { if (!allowed()) return; s = K.make(selectedTrack, selectedCar); skid = []; shown = false; running = true; paused = false; accumulator = 0; clearInput(); $('menu').hidden = true; $('result').hidden = true; $('controls').hidden = false; $('hud').hidden = false; tone(600); }
  function result(finish) { paused = true; clearInput(); $('result').hidden = false; $('result-icon').textContent = finish ? '🏆' : 'Ⅱ'; $('result-title').textContent = finish ? '¡Dos vueltas!' : 'Pausa'; $('result-stats').textContent = finish ? '⭐ ' + Math.round(s.time) + ' s  ·  🏁 ✓ ✓' : K.tracks[s.track].icon + '  🚘'; $('next').setAttribute('aria-label', finish ? 'Siguiente circuito' : 'Continuar'); }
  $('play').onclick = start; $('retry').onclick = start;
  $('next').onclick = function () { if (!allowed()) return; if (s.finished) { selectedTrack = (selectedTrack + 1) % K.tracks.length; $('tracks').querySelectorAll('button')[selectedTrack].click(); start(); } else { paused = false; accumulator = 0; $('result').hidden = true; } };
  $('garage').onclick = function () { if (!allowed()) return; running = false; paused = false; $('result').hidden = true; $('menu').hidden = false; $('controls').hidden = true; $('hud').hidden = true; clearInput(); };
  $('pause').onclick = function () { if (!allowed() || !running || s.finished) return; if (paused) $('next').click(); else result(false); };
  $('assist').onclick = function () { if (!allowed()) return; input.assist = !input.assist; $('assist').setAttribute('aria-pressed', String(input.assist)); $('assist').setAttribute('aria-label', 'Aceleración suave automática ' + (input.assist ? 'activada' : 'desactivada')); $('assist').textContent = input.assist ? '🤝 ✓' : '🤝 ○'; };
  $('help').onclick = function () { if (allowed()) $('guide').hidden = !$('guide').hidden; };
  $('sound').onclick = function () { if (!allowed()) return; sound = !sound; $('sound').textContent = sound ? '🔊' : '🔇'; $('sound').setAttribute('aria-label', sound ? 'Desactivar sonido' : 'Activar sonido'); $('sound').setAttribute('aria-pressed', String(sound)); if (sound && audio) audio.resume().catch(function () {}); tone(650); };
  document.querySelectorAll('[data-input]').forEach(function (b) { b.addEventListener('pointerdown', function (e) { if (!allowed() || !running || paused) return; e.preventDefault(); input[b.dataset.input] = true; pointerKeys[e.pointerId] = b.dataset.input; b.classList.add('held'); try { b.setPointerCapture(e.pointerId); } catch (_) {} }); function up(e) { delete pointerKeys[e.pointerId]; input[b.dataset.input] = Object.keys(pointerKeys).some(function (id) { return pointerKeys[id] === b.dataset.input; }); b.classList.remove('held'); } b.addEventListener('pointerup', up); b.addEventListener('pointercancel', up); b.addEventListener('lostpointercapture', up); });
  var keyMap = { ArrowLeft: 'left', a: 'left', ArrowRight: 'right', d: 'right', ArrowUp: 'throttle', w: 'throttle', ArrowDown: 'brake', s: 'brake' };
  addEventListener('keydown', function (e) { if (!allowed()) return; if (e.key === 'Escape') $('pause').click(); if (keyMap[e.key] && running && !paused) { e.preventDefault(); input[keyMap[e.key]] = true; } });
  addEventListener('keyup', function (e) { if (keyMap[e.key]) input[keyMap[e.key]] = false; }); addEventListener('blur', clearInput); document.addEventListener('visibilitychange', function () { clearInput(); last = 0; accumulator = 0; }); addEventListener('resize', resize);
  function path() { ctx.beginPath(); s.points.forEach(function (p, i) { if (i) ctx.lineTo(p.x, p.y); else ctx.moveTo(p.x, p.y); }); ctx.closePath(); }
  function kart(x, y, angle, color, ghost) {
    ctx.save(); ctx.translate(x, y); ctx.rotate(angle + Math.PI / 2); var scale = Math.max(1, .63 / zoom); ctx.scale(scale, scale); if (ghost) ctx.globalAlpha = .42;
    ctx.fillStyle = '#15372d50'; ctx.beginPath(); ctx.ellipse(3, 5, 18, 24, 0, 0, Math.PI * 2); ctx.fill();
    ctx.fillStyle = '#152b31'; ctx.fillRect(-17, -13, 8, 12); ctx.fillRect(9, -13, 8, 12); ctx.fillRect(-17, 9, 8, 14); ctx.fillRect(9, 9, 8, 14);
    ctx.fillStyle = color; ctx.beginPath(); ctx.moveTo(-12, 19); ctx.lineTo(-13, -10); ctx.quadraticCurveTo(-11, -24, 0, -25); ctx.quadraticCurveTo(11, -24, 13, -10); ctx.lineTo(12, 19); ctx.closePath(); ctx.fill();
    ctx.fillStyle = '#e9f4d870'; ctx.fillRect(-7, -19, 14, 5); ctx.fillStyle = '#234244'; ctx.fillRect(-8, -4, 16, 14); ctx.fillStyle = '#e4f8e2'; ctx.beginPath(); ctx.arc(0, 2, 5, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#234244'; ctx.fillRect(-6, 0, 12, 3);
    ctx.fillStyle = color; ctx.fillRect(-18, 19, 36, 5); ctx.fillStyle = '#ffffff70'; ctx.fillRect(-10, -12, 3, 24); ctx.restore();
  }
  function draw() {
    var t = K.tracks[s.track]; ctx.fillStyle = t.ground; ctx.fillRect(0, 0, w, h);
    ctx.save(); ctx.translate(cx, cy); ctx.scale(zoom, zoom);
    for (var i = 0; i < 50; i++) { var tx = (i * 137 % 970) - 485, ty = (i * 211 % 790) - 395; if (K.nearest(tx, ty, s.points).distance < 87) continue; if (s.track === 1) { ctx.strokeStyle = '#d1f5e955'; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(tx, ty, 13, .1, 2.8); ctx.stroke(); } else { ctx.fillStyle = '#153c3040'; ctx.beginPath(); ctx.ellipse(tx + 4, ty + 11, 15, 8, 0, 0, 7); ctx.fill(); ctx.fillStyle = s.track === 2 ? '#7b9a6c' : '#71a576'; ctx.beginPath(); ctx.arc(tx, ty, 14 + i % 6, 0, 7); ctx.fill(); ctx.fillStyle = '#ffffff18'; ctx.beginPath(); ctx.arc(tx - 5, ty - 5, 7, 0, 7); ctx.fill(); } }
    ctx.lineJoin = 'round'; ctx.lineCap = 'round'; path(); ctx.strokeStyle = '#264e4233'; ctx.lineWidth = 143; ctx.stroke(); path(); ctx.strokeStyle = t.edge; ctx.lineWidth = 124; ctx.stroke(); path(); ctx.strokeStyle = '#faeee0'; ctx.lineWidth = 109; ctx.stroke(); ctx.setLineDash([18, 18]); ctx.strokeStyle = '#d8766a'; ctx.stroke(); ctx.setLineDash([]); path(); ctx.strokeStyle = t.road; ctx.lineWidth = 96; ctx.stroke(); path(); ctx.lineWidth = 2; ctx.strokeStyle = '#eaf0da68'; ctx.setLineDash([13, 24]); ctx.stroke(); ctx.setLineDash([]);
    ctx.font = 'bold 22px sans-serif'; ctx.textAlign = 'center'; ctx.fillStyle = '#f1efd599'; ctx.fillText(K.tracks[s.track].icon, 0, -20); ctx.font = 'bold 17px sans-serif'; ctx.fillText('MINI KARTS', 0, 15);
    var start = s.points[0], nextPoint = s.points[1], a = Math.atan2(nextPoint.y - start.y, nextPoint.x - start.x);
    ctx.save(); ctx.translate(start.x, start.y); ctx.rotate(a); for (var row = 0; row < 2; row++) for (var col = 0; col < 10; col++) { ctx.fillStyle = (row + col) % 2 ? '#213c40' : '#fff1d2'; ctx.fillRect(row * 8 - 8, col * 9 - 45, 8, 9); } ctx.restore();
    ctx.lineWidth = 2; ctx.strokeStyle = '#253a3a55'; skid.forEach(function (p) { ctx.beginPath(); ctx.moveTo(p.x, p.y); ctx.lineTo(p.x + Math.cos(p.angle) * 9, p.y + Math.sin(p.angle) * 9); ctx.stroke(); });
    var target = s.points[s.next * 10], targetNext = s.points[(s.next * 10 + 4) % 120], ta = Math.atan2(targetNext.y - target.y, targetNext.x - target.x);
    if (running) { ctx.save(); ctx.translate(target.x, target.y); ctx.rotate(ta); ctx.fillStyle = '#ffea99'; ctx.globalAlpha = .65 + Math.sin(s.time * 3) * .2; ctx.beginPath(); ctx.moveTo(-14, -14); ctx.lineTo(8, 0); ctx.lineTo(-14, 14); ctx.lineTo(-7, 0); ctx.closePath(); ctx.fill(); ctx.restore(); }
    // Transparent pace karts are visual ghosts, not collidable opponents.
    if (running) [0, 1].forEach(function (g) { var phase = (s.time * (4.1 + g * .5) + 3 + g * 4) % 120, index = Math.floor(phase), p = s.points[index], q = s.points[(index + 1) % 120]; kart(p.x + (q.x - p.x) * (phase - index), p.y + (q.y - p.y) * (phase - index), Math.atan2(q.y - p.y, q.x - p.x), g ? '#d8c2fa' : '#fff3c7', true); });
    kart(s.x, s.y, s.angle, K.cars[s.car].color, false); ctx.restore();
  }
  function frame(now) { requestAnimationFrame(frame); if (gate) gate.check(); var dt = last ? Math.min(.08, (now - last) / 1000) : 0; last = now;
    if (!document.hidden && running && !paused && !blocked) { accumulator += dt; while (accumulator >= 1 / 120) { var oldGate = s.gates; K.step(s, input, 1 / 120); if (s.gates !== oldGate) tone(s.laps ? 700 : 430); accumulator -= 1 / 120; } if ((input.left || input.right) && s.speed > 90 && Math.floor(s.time * 30) % 2 === 0) { skid.push({ x: s.x, y: s.y, angle: s.angle }); if (skid.length > 150) skid.shift(); } if (s.finished && !shown) { shown = true; tone(900); result(true); } } else accumulator = 0;
    $('laps').textContent = '🏁 ' + (s.laps > 0 ? '✓' : '○') + ' ' + (s.laps > 1 ? '✓' : '○'); $('checkpoints').textContent = '➜ ' + (s.gates % 12) + ' / 12'; $('clock').textContent = Math.floor(s.time) + ' s'; draw();
  }
  resize();
  if (window.LearningGate) gate = LearningGate.mount({ gameId: 'pocket-karts', onLock: function () { blocked = true; clearInput(); last = 0; accumulator = 0; if (audio) audio.suspend().catch(function () {}); }, onUnlock: function () { blocked = false; last = 0; accumulator = 0; if (sound && audio) audio.resume().catch(function () {}); } });
  else { $('play').disabled = true; $('guide').hidden = false; $('guide').textContent = 'No se pudo cargar el reto. Recarga la página.'; }
  if (location.search.indexOf('test=1') !== -1) Object.defineProperty(window, '__karts', { get: function () { return { running: running, paused: paused, blocked: blocked, sound: sound, x: s.x, y: s.y, angle: s.angle, speed: s.speed, laps: s.laps, next: s.next, gates: s.gates, finished: s.finished, track: s.track, car: s.car, time: s.time, held: Object.keys(input).filter(function (k) { return k !== 'assist' && input[k]; }) }; } });
  if ('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js', { updateViaCache: 'none' }).catch(function () {});
  requestAnimationFrame(frame);
})();
